name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: [main]
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    strategy:
      matrix:
        build_type: [Release]
        os: [windows-2022, ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install build deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ pkg-config

      - name: Set up MSVC (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86_64

      - name: Set up CMake & Ninja
        uses: lukka/get-cmake@latest

      - name: Configure (Linux)
        if: runner.os == 'Linux'
        run: >
          cmake
          -S .
          -B build/${{ matrix.build_type }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: >
          cmake
          -S .
          -B build/${{ matrix.build_type }}
          -G Ninja
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_CXX_COMPILER=cl

      - name: Build
        run: cmake --build build/${{ matrix.build_type }} --parallel

      - name: Run tests
        run: ctest --test-dir build/${{ matrix.build_type }} --output-on-failure
